# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ugrad/abueide/trace

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ugrad/abueide/trace

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ugrad/abueide/trace/CMakeFiles /home/ugrad/abueide/trace/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ugrad/abueide/trace/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PrcessTrace

# Build rule for target.
PrcessTrace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PrcessTrace
.PHONY : PrcessTrace

# fast build rule for target.
PrcessTrace/fast:
	$(MAKE) -f CMakeFiles/PrcessTrace.dir/build.make CMakeFiles/PrcessTrace.dir/build
.PHONY : PrcessTrace/fast

PrcessTrace.o: PrcessTrace.c.o

.PHONY : PrcessTrace.o

# target to build an object file
PrcessTrace.c.o:
	$(MAKE) -f CMakeFiles/PrcessTrace.dir/build.make CMakeFiles/PrcessTrace.dir/PrcessTrace.c.o
.PHONY : PrcessTrace.c.o

PrcessTrace.i: PrcessTrace.c.i

.PHONY : PrcessTrace.i

# target to preprocess a source file
PrcessTrace.c.i:
	$(MAKE) -f CMakeFiles/PrcessTrace.dir/build.make CMakeFiles/PrcessTrace.dir/PrcessTrace.c.i
.PHONY : PrcessTrace.c.i

PrcessTrace.s: PrcessTrace.c.s

.PHONY : PrcessTrace.s

# target to generate assembly for a file
PrcessTrace.c.s:
	$(MAKE) -f CMakeFiles/PrcessTrace.dir/build.make CMakeFiles/PrcessTrace.dir/PrcessTrace.c.s
.PHONY : PrcessTrace.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PrcessTrace"
	@echo "... PrcessTrace.o"
	@echo "... PrcessTrace.i"
	@echo "... PrcessTrace.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

